/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * question_paper.java
 *
 * Created on Jul 11, 2010, 4:10:12 PM
 */

/**
 *
 * @author jalatif abhi
 */
import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import java.awt.Toolkit;
import javax.swing.*;
public class question_paper extends javax.swing.JFrame {
Timer timer;
Toolkit toolkit;
static int i=0,j=2,k=0;
static int q=1,n=new question_set().qnos,r=0,ls=0;
static String d[]=new question_set().d.clone();//{"Who is Splinter Cell's Hero ?","When Was prince of persia released for pc ?","Payal song belongs to which band ?","Which team won d FIfa WorldCup 2010 ?","Who is leading character of Saboteur?"};
static String e[][]=new question_set().e.clone();//{{"Kyne","Lynch","Sam Fisher","Max"},{"14-04-10","13-05-10","27-05-10","08-06-10"},{"Strings","Jal","Atif","Raeth"},{"Spain","Netherland","Germany","Brazil"},{"Sean Devlin","Dastan","Stanley","Jason Statham"}};
static int s[]=new question_set().s.clone();//{0,0,0,0,0};
static int ans[]=new question_set().ans.clone();//{3,4,2,1,1};
static int u[]=s.clone();//{0,0,0,0,0};
static int nkp=0,max=0;
/** Creates new form question_paper */
    public question_paper() {
        initComponents();
        setTitle("Test Proceeding");
        setSize(1200,600);
        //question_set obj=new question_set();
        Test_Timer obj1=new Test_Timer(1);
        i=obj1.tm[0];j=obj1.tm[1];k=obj1.tm[2];
        /*n=obj.qnos;
        d=obj.d.clone();
        e=obj.e.clone();
        s=obj.s.clone();
        u=s.clone();
        ans=obj.ans.clone();*/
        max=i*60*60+j*60+k;
        jpb1.setStringPainted(true);
        jpb1.setForeground(Color.blue);
        jpb1.setBorderPainted(true);
        jpb1.setMaximum(max);
        nkp=0;
        jpb1.setValue(nkp);
        System.out.println(n+" "+ans[0]);
       combos();
        set_question(1);

        toolkit=Toolkit.getDefaultToolkit();
        timer=new Timer();
        timer.schedule(new CountDownTimer(),0,1*1000);

    }
    public void combos(){
          //jComboBox1.removeAllItems();
        for (int js=2;js<=n;js++){
            jComboBox1.addItem(js);//.addItem(js+1);
    }
          }
    class CountDownTimer extends TimerTask{
     public void run(){
         nkp++;
        jpb1.setValue(nkp);
        String s4=jLabel1.getText();
        String s5=jLabel2.getText();
        String s6=jLabel3.getText();
        if (s4.equals("   0")&&s5.equals("   0")&&s6.equals("   0"))
        {
            toolkit.beep();
            toolkit.beep();

           timer.cancel();
             k=0;
             if ( (check_answer(q)==button_assign(q) ) || (s[q-1]==1 &&button_assign(q)==0) )
                      {s[q-1]=1;}
             else
                      {s[q-1]=0;}
            for (int t=0;t<n;++t)
                     r+=s[t];
            //System.out.println("Result = "+r+" Correct out of "+n);
            setVisible(false);new Calculator().setVisible(false);
            new test_result().setVisible(true);
            //System.exit(0);
        }
       if (k>=0)
        {
            String s1 = "   "+String.valueOf(i);
            String s2="   "+String.valueOf(j);
            String s3="   "+String.valueOf(k);
            jLabel1.setText(s1);
            jLabel2.setText(s2);
            jLabel3.setText(s3);
            k--;
         }
       else{if (j>0){
            k=59;j--;toolkit.beep();
            String s1="   "+String.valueOf(i);
            String s2="   "+String.valueOf(j);
            String s3="   "+String.valueOf(k);
            jLabel1.setText(s1);
            jLabel2.setText(s2);
            jLabel3.setText(s3);
            k--;
       }
 else{
        i--;k=59;j=59;toolkit.beep();
        String s1="   "+String.valueOf(i);
            String s2="   "+String.valueOf(j);
            String s3="   "+String.valueOf(k);
            jLabel1.setText(s1);
            jLabel2.setText(s2);
            jLabel3.setText(s3);
            k--;
 }
         }
      }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jpb1 = new javax.swing.JProgressBar();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("   HH");

        jLabel5.setText("   MM");

        jLabel6.setText("   SS");

        jLabel7.setText("Time Left");

        jLabel8.setText("j");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("1st Option");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("2nd Option");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("3rd Option");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("4th Option");

        jLabel9.setText("  a)");

        jLabel10.setText("  b)");

        jLabel11.setText("  c)");

        jLabel12.setText("  d)");

        jButton1.setText("Previous");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Finish");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Jump to Question");

        jLabel14.setText("by JALATIF");

        jInternalFrame1.setVisible(true);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
        );

        jButton4.setText("Use Calculator");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(jpb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(172, 172, 172))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel11, 0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jRadioButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButton2))
                        .addGap(108, 108, 108)
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addGap(25, 25, 25)))
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jRadioButton1))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton3)
                                    .addComponent(jButton4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jpb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 public  void set_question(int q){
        put_List(check_undone());
        buttonGroup1.clearSelection();
        jLabel8.setText("    Q"+String.valueOf(q)+". "+d[q-1]+"?");
        jRadioButton1.setText(e[q-1][0]);
        jRadioButton2.setText(e[q-1][1]);
        jRadioButton3.setText(e[q-1][2]);
        jRadioButton4.setText(e[q-1][3]);
        button_mark(u[q-1]);
        pack();
        /*if (ls==0){
         combos();ls++;
        }*/
}
public void button_mark(int v){
X:
switch (v)
{case 1:{jRadioButton1.setSelected(true);break X;}
 case 2:{jRadioButton2.setSelected(true);break X;}
 case 3:{jRadioButton3.setSelected(true);break X;}
 case 4:{jRadioButton4.setSelected(true);break X;}
    default:break X;
}
}

public int button_assign(int q){
    if (jRadioButton1.isSelected())
    {u[q-1]=1;
        return 1;}
    if (jRadioButton2.isSelected())
    {u[q-1]=2;
        return 2;}
    if (jRadioButton3.isSelected())
    {u[q-1]=3;
        return 3;}
    if (jRadioButton4.isSelected())
    {u[q-1]=4;
        return 4;}
    else
    { u[q-1]=0;return 0;}
}
public int check_answer(int q){
/*switch (q)
    {case 1:{return 3;}
    case 2:{return 4;}
    case 3:{return 2;}
    case 4:{return 1;}
    case 5:{return 1;}
    default:{return 0;}
}*/
return ans[q-1];
}
public void put_List(String g){
jTextArea1.removeAll();
jTextArea1.setText("Questions-\nunmarked:-\n");
StringBuffer c= new StringBuffer(0);int f=1;
c.append(g);
for (int u=0;u<c.length();u++){
      if (u==13*f){
      jTextArea1.append("\n");
      f++;
      u--;
      }
    else{String g1=String.valueOf(c.charAt(u));
     //System.out.print(g1);
      jTextArea1.append(g1);
    }
  }
pack();
}
public String check_undone(){
StringBuffer l= new StringBuffer(0);
for (int e=0;e<n;++e){
 if (u[e]==0){
 l.append(String.valueOf(e+1));
    if (e!=n-1){
    l.append(", ");    
    }
 }
     
}
String g2=String.valueOf(l);
//System.out.println(g2);
return g2;
}

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if ( (check_answer(q)==button_assign(q) ) || (s[q-1]==1 &&button_assign(q)==0) )
       {s[q-1]=1;}
else
       {s[q-1]=0;}
/*jRadioButton1.hide();
jRadioButton2.hide();
jRadioButton3.hide();
jRadioButton4.hide();*/
/*jRadioButton1.setVisible(true);
jRadioButton2.setVisible(true);
jRadioButton3.setVisible(true);
jRadioButton4.setVisible(true);
*/

   if (q!=n)
        q++;
    else
        q=1;
set_question(q);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  if (  (check_answer(q)==button_assign(q) )   || (s[q-1]==1 &&button_assign(q)==0) )
       {s[q-1]=1;}
  else
       {s[q-1]=0;}

   if (q!=1)
            q--;
        else
            q=n;
       set_question(q);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
 if ( (check_answer(q)==button_assign(q) ) || (s[q-1]==1 &&button_assign(q)==0) )
       {s[q-1]=1;}
 else
       {s[q-1]=0;}
 q=Integer.parseInt(String.valueOf(jComboBox1.getModel().getSelectedItem()));
 set_question(q);
 // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if ( (check_answer(q)==button_assign(q) ) || (s[q-1]==1 &&button_assign(q)==0) )
       {s[q-1]=1;}
else
       {s[q-1]=0;}
   for (int t=0;t<n;++t)
       r+=s[t];
   System.out.println("Result = "+r+" Correct out of "+n);
   timer.cancel();
   setVisible(false);
   new test_result().setVisible(true);
   //System.exit(0);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Calculator obsg=new Calculator();
obsg.setVisible(true);
obsg.setAlwaysOnTop(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
     Thread obj=Thread.currentThread();
     obj.setPriority(9);
        try {
	    // Set System L&F
        //UIManager.setLookAndFeel( UIManager.getSystemLookAndFeelClassName());
  }
catch(Exception e){
    System.out.println(e);
}
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                       /*if (new login_test().y1==0)
        {
         new question_paper().setVisible(false);
         new Error_Order().setVisible(true); }
 else*/
                new question_paper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    public static javax.swing.JComboBox jComboBox1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JProgressBar jpb1;
    // End of variables declaration//GEN-END:variables

}
