/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * View_Questions.java
 *
 * Created on Jul 19, 2010, 5:45:48 PM
 */

/**
 *
 * @author jalatif abhi
 */
import java.sql.*;
import java.util.*;
import javax.swing.*;
public class View_Questions extends javax.swing.JFrame {
static Connection con=null;
//static Vector v[]=new Vector [5];
static Vector v0=new Vector(0);
static Vector v1=new Vector(0);
static Vector v2=new Vector(0);
static Vector v3=new Vector(0);
static Vector v4=new Vector(0);
static Vector n1=new Vector(0);
static Vector n2=new Vector(0);
static int lx=0,mx=0,ex=0;
static String st[]=new String[7];
static int or[];
/** Creates new form View_Questions */
    public View_Questions() {
        initComponents();
        setSize(1020,700);
        setTitle("View n Modify Questions");
        //view_table(1);
        /*for(int is=0;is<7;is++){
         st[is]=null;
        }*/
        jLabel3.setText(null);
        view_table(0);
       }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Qno.", "Question", "Option1", "Option2", "Option3", "Option4", "Ans"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(40);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(6).setMaxWidth(40);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Finish");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Move Ques");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

        jLabel2.setText("to");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

        jButton3.setText("Ok");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        jButton4.setText("Save Settings");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Delete All");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel4.setText("Delete Ques");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

        jButton6.setText("Ok");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel5.setText("Edit Ques");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

        jButton7.setText("Ok");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Set Order Manually");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Set");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Set");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Change Test Time");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Add Questions");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jButton3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton9)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton7)
                            .addGap(6, 6, 6)
                            .addComponent(jButton10))))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jButton12)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton11))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton10)))
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5)
                    .addComponent(jButton2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if (mx==0){
String s1=String.valueOf(jComboBox1.getSelectedItem());
String s2=String.valueOf(jComboBox2.getSelectedItem());
if (s1.equals("---")||s2.equals("---")){
jLabel3.setText("Invalid Move");
}
 else{mx=1;
int n1=Integer.parseInt(s1);
int n2=Integer.parseInt(s2);
//jTable1.getModel().setValueAt(jTable1, WIDTH, WIDTH)
    if (n1>n2){
      jTable1.getModel().setValueAt(n1, n2, 0);
      jTable1.getModel().setValueAt(n2, n2+1, 0);int r=1;
    for (int ns=n2+2;ns<=n1;ns++){
     jTable1.getModel().setValueAt(n2+r++, ns, 0);
    }

    }
    if (n2>n1){
      jTable1.getModel().setValueAt(n1, n2, 0);
      jTable1.getModel().setValueAt(n2, n2-1, 0);int r=1;
    for (int ns=n2-2;ns>=n1;ns--){
     jTable1.getModel().setValueAt(n2-r++, ns, 0);
    }

    }
 }
        }
 else{
    jLabel3.setText("First Save These Settings");
 }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
int l=1;
lx=1;mx=0;
for (int js=1;js<=qno();js++){
   if (Integer.parseInt(String.valueOf(jTable1.getModel().getValueAt(js, 0)))==l){
    put_correct(js);
    js=0;l++;lx=0;
   }
}
//lx=0;
setVisible(false);
new Fake();
//view_table(0);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
setVisible(false);
new Del_Protect(2).setVisible(true);
/*connect();
try{
    PreparedStatement p=con.prepareCall("delete from questions");
    p.executeUpdate();
    view_table(0);
}
catch(Exception e){
    System.out.println(e);
}*/
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
try{
        int dj=Integer.parseInt(String.valueOf(jComboBox3.getSelectedItem()));
jTable1.getModel().setValueAt(0, dj, 0);jTable1.getModel().setValueAt("Deleted", dj, 1);jTable1.getModel().setValueAt("Deleted", dj, 2);
jTable1.getModel().setValueAt("Deleted", dj, 3);jTable1.getModel().setValueAt("Deleted", dj, 4);jTable1.getModel().setValueAt("Deleted", dj, 5);
jTable1.getModel().setValueAt("N.A", dj, 6);
int rs=dj+1;
for(int js=dj;js<qno();++js){
jTable1.getModel().setValueAt(js, rs++, 0);
}
        }
catch(Exception e){
    System.out.println(e);
    jLabel3.setText("Enter Valid QuesNo");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        try{
        int ms=Integer.parseInt(String.valueOf(jComboBox4.getSelectedItem()));
       st[0]=String.valueOf(ms);
       //System.out.println(st[0]+"a");
        for (int is=1;is<7;is++)
{
    st[is] = String.valueOf(jTable1.getModel().getValueAt(ms, is));
      // System.out.println(st[is]+"a");
        }

        //setVisible(false);
        new Edit_Question().setVisible(true);
        new Edit_Question().setAlwaysOnTop(true);
        }
catch(Exception e){
    System.out.println(e);
    jLabel3.setText("Enter Valid QuesNo");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
Set_Order obj=new Set_Order();
obj.setVisible(true);
        obj.setAlwaysOnTop(true);
   
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
Set_Order obj=new Set_Order();
        ques_order_set(obj);
for (int i=0;i<or.length;++i){
jTable1.getModel().setValueAt(or[i], i+1, 0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
Edit_Question obj=new Edit_Question();
int q=obj.q;//Integer.parseInt(String.valueOf(jComboBox4.getSelectedItem()));
int an=obj.an;
String s[]=obj.s;
int i=1;
jTable1.getModel().setValueAt(s[0], q, i++);
jTable1.getModel().setValueAt(s[1], q, i++);
jTable1.getModel().setValueAt(s[2], q, i++);
jTable1.getModel().setValueAt(s[3], q, i++);
jTable1.getModel().setValueAt(s[4], q, i++);
jTable1.getModel().setValueAt(an, q, i++);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
setVisible(false);
new Adminstrator_Field().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
new Set_Time().setVisible(true);
new Set_Time().setAlwaysOnTop(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
setVisible(false);
new Questions_Add().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed
public void put_correct(int a){
connect();
try{
if (lx==1){
    PreparedStatement p0=con.prepareCall("delete  from questions");
p0.executeUpdate();
    }
String s[]={String.valueOf(jTable1.getModel().getValueAt(a, 0)),String.valueOf(jTable1.getModel().getValueAt(a, 1)),String.valueOf(jTable1.getModel().getValueAt(a, 2)),String.valueOf(jTable1.getModel().getValueAt(a, 3)),String.valueOf(jTable1.getModel().getValueAt(a, 4)),String.valueOf(jTable1.getModel().getValueAt(a, 5)),String.valueOf(jTable1.getModel().getValueAt(a, 6))};
PreparedStatement p1=con.prepareCall("insert into questions values(?,?,?,?,?,?,?)");
p1.setInt(1,Integer.parseInt(s[0]));
p1.setString(2,s[1]);
p1.setString(3,s[2]);
p1.setString(4,s[3]);
p1.setString(5,s[4]);
p1.setString(6,s[5]);
p1.setInt(7,Integer.parseInt(s[6]));
p1.executeUpdate();
}
catch(Exception e){
    System.out.println(e);
}
}
    /**
    * @param args the command line arguments
    */

public int qno(){
for (int r=1;;r++)
{
    if (jTable1.getModel().getValueAt(r, 0)==null){
        return r-1;
    }
}
    }
public void ques_order_set(Set_Order obj){
    //Set_Order obj=new Set_Order();

    or=new int[qno()];
    or=obj.or;
     for (int i=0;i<or.length;++i){
        //System.out.println(obj.or[i]);
         System.out.println(or[i]);}
}

public void combos(){
jComboBox1.removeAllItems();jComboBox2.removeAllItems();
jComboBox3.removeAllItems();jComboBox4.removeAllItems();
jComboBox2.addItem("---");jComboBox1.addItem("---");
jComboBox3.addItem("---");jComboBox4.addItem("---");
for (int r=1;r<=qno();r++){
jComboBox1.addItem(r);jComboBox2.addItem(r);
jComboBox3.addItem(r);jComboBox4.addItem(r);
}

}
public void connect(){
    try
        {String url = "jdbc:mysql://localhost:5131/";
            String dbName = "Test_Questions";
            String driver = "com.mysql.jdbc.Driver";
            String userName = "root";
            String password = "poptfs";
           Class.forName(driver).newInstance();
           con = DriverManager.getConnection(url+dbName,userName,password);
           System.out.println("Driver Loaded");
        }
        catch (Exception e)
        {System.out.println(e);
        }
    }
public void view_table(int a){
if (a==0){
connect();
try{
    PreparedStatement p=con.prepareCall("select * from questions order by QNo");
    ResultSet r=p.executeQuery();
/*for (int i=0;i<5;++i){
v[i].removeAllElements();
}*/
v0.removeAllElements();v1.removeAllElements();v2.removeAllElements();
v3.removeAllElements();v4.removeAllElements();n1.removeAllElements();
n2.removeAllElements();

while (r.next()){
n1.add(r.getInt(1));
v0.add(r.getString(2));
v1.add(r.getString(3));
v2.add(r.getString(4));
v3.add(r.getString(5));
v4.add(r.getString(6));
n2.add(r.getInt(7));
}
//System.out.println(v0);
//for (int j=1;j<5;++j){
for (int i=0;i<v0.size();i++){
String z=String.valueOf(v0.elementAt(i));
String y[]=z.split("   ");
v0.setElementAt(y[0], i);
}
//}
for (int i=0;i<v1.size();i++){
String z=String.valueOf(v1.elementAt(i));
String y[]=z.split("   ");
v1.setElementAt(y[0], i);
}
for (int i=0;i<v2.size();i++){
String z=String.valueOf(v2.elementAt(i));
String y[]=z.split("   ");
v2.setElementAt(y[0], i);
}
for (int i=0;i<v3.size();i++){
String z=String.valueOf(v3.elementAt(i));
String y[]=z.split("   ");
v3.setElementAt(y[0], i);
}
for (int i=0;i<v4.size();i++){
String z=String.valueOf(v4.elementAt(i));
String y[]=z.split("   ");
v4.setElementAt(y[0], i);
}
/*System.out.println(v0);
System.out.println(v1);
System.out.println(v2);
System.out.println(v3);
System.out.println(v4);
System.out.println(n1);
System.out.println(n2);*/
int j=1;
for(int i=0;i<n1.size();i++){
String s[]={String.valueOf(n1.elementAt(i)),String.valueOf(v0.elementAt(i)),String.valueOf(v1.elementAt(i)),String.valueOf(v2.elementAt(i)),String.valueOf(v3.elementAt(i)),String.valueOf(v4.elementAt(i)),String.valueOf(n2.elementAt(i))};
jTable1.getModel().setValueAt(s[0],j,0);
jTable1.getModel().setValueAt(s[1],j,1);
jTable1.getModel().setValueAt(s[2],j,2);
jTable1.getModel().setValueAt(s[3],j,3);
jTable1.getModel().setValueAt(s[4],j,4);
jTable1.getModel().setValueAt(s[5],j,5);
jTable1.getModel().setValueAt(s[6],j,6);
j++;
}
//System.out.println(String.valueOf(jTable1.getModel().getValueAt(2, 1)));
System.out.println(qno());
combos();
}
catch(Exception e){
    System.out.println(e);
}
}
if (a==1){
connect();
try{
PreparedStatement p=con.prepareCall("delete from questions");
p.executeUpdate();
}
catch(Exception e){
    System.out.println(e);
}
}
}
public static void main(String args[]) {
      try {
	    // Set System L&F
        //UIManager.setLookAndFeel( UIManager.getSystemLookAndFeelClassName());
  }
catch(Exception e){
    System.out.println(e);
}
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (new Start().z==0){
                new Error_Order().setVisible(true);}
                else
                new View_Questions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    public javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
